#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: UCARE AZ
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  A Young group actively  helping local communities;
  UCARE is a non-profit corporation and should be operated exclusively for educational and development purpose within the meaning of section 501(c)(3)of the IR Code of 1986. It aims to develop youth leadership via workshops and volunteer activities.;
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Our nonprofit organization is dedicated to empowering individuals and groups to actively engage in meaningful service within their local communities. We focus on creating lasting impact through compassionate outreach to underserved populations, including senior citizens in care homes, Native Tribes, families facing hunger, and children with limited access to educational resources such as books. By fostering collaboration, inclusivity, and volunteer-driven initiatives, we strive to build stronger, more connected communities. Our programs are designed to meet immediate needs while promoting long-term support and awareness, ensuring that no voice is unheard and no need goes unmet. Together, we believe in the power of people helping people—one community at a time.
  
#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: ally99.xu@gmail.com
org_street_address: 1771 W maplewood Pl #Please include suite number on the line below
org_address_suite: 
org_city: Chandler 
org_state: AZ
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  85286
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (480) 818-5676

#SOCIAL MEDIA
org_twitter_username: ucareaz
org_facebook_username: ucareaz
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
